{
  "comments": [
    {
      "key": {
        "uuid": "1af78d9a_3f312f0c",
        "filename": "brain/midonet-brain/src/main/scala/org/midonet/brain/services/c3po/C3POStorageManager.scala",
        "patchSetId": 14
      },
      "lineNbr": 130,
      "author": {
        "id": 1002760
      },
      "writtenOn": "2014-12-23T16:25:37Z",
      "side": 1,
      "message": "We still need to wrap around storage.get with a try-catch. Storage doesn\u0027t throw Processing Exception.",
      "range": {
        "startLine": 125,
        "startChar": 4,
        "endLine": 130,
        "endChar": 5
      },
      "revId": "200c0e0066167c1085004f2bbdc2cbc912829ee0",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}